POST http://localhost:4001/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc0MjA5MTgzNywiZXhwIjoxNzQyMDk1NDM3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.YaX01q8LkOPgNXVOk08yI-4iWvrZc6vHYncyNvmE4zs
{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJpYXQiOjE3NDIwOTE4MzcsImV4cCI6MTc0MjE3ODIzNywiYXVkIjoibG9jYWxob3N0OjMwMDEiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMSJ9.e9gUr4qe2XSF8kydgc4xwgvemGiLfkwRbX5Vd9AfcWA"
}